name: gmx_MMPBSA_ana Bug Report
description: Report a bug or issue with gmx_MMPBSA.
title: "[Bug-gmx_MMPBSA_ana]: "
body:
  - type: textarea
    id: summary
    attributes:
      label: Bug summary
      description:  Describe the bug in 1-2 short sentences
      placeholder:
      value:
    validations:
      required: true
  - type: textarea
    id: pront
    attributes:
      label: Terminal output
      description: Provides the output of your terminal
      placeholder: Paste your terminal output here
      render: bash
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual outcome
      description: |
        Paste the output, e.g. console output, images/videos, any relevant screenshots/screencasts, etc.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected outcome
      description: Describe (or provide a visual example of) the expected outcome.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Additional information
      description: |
        - What are the conditions under which this bug happens? input parameters, edge cases, etc?
        - Has this worked in earlier versions?
  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: Windows, Window Subsystem for Linux, OS/X, Arch, Debian, Ubuntu, etc.
  - type: input
    id: gmx_mmpbsa-version
    attributes:
      label: gmx_MMPBSA Version
      description: "In terminal: `gmx_MMPBSA -v`"
  - type: input
    id: python-version
    attributes:
      label: Python version
      description: "In console: `python --version`"
  - type: dropdown
    id: install
    attributes:
      label: Installation
      description: How did you install gmx_MMPBSA?
      options:
        - pip
        - AmberTools compilation + pip
        - AmberTools compilation + conda
        - conda AmberTools + pip
        - conda AmberTools + conda
        - from source (.tar.gz)
        - git checkout
